export let API_FETCHING="API_FETCHING";
export let API_FETCH_SUCCESS="API_FETCH_SUCCESS";
export let API_FETCH_FAIL="API_FETCH_FAIL";


export let ADD_NEW_ITEM_TOCART="ADD_NEW_ITEM_TOCART";
export let REMOVE_ITEM_FROM_CART="REMOVE_ITEM_FROM_CART";